# -*- coding: utf-8 -*-
"""matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13aDw9wtUcayMjKbtWFW7qLDwKr2rBMhQ
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/dailyActivity_merged.csv')
df

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.plot(df['ActivityDate'].head(5), df['Calories'].head(5))
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.plot(df['ActivityDate'], df['Calories'])
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.plot(df['ActivityDate'].head(10), df['Calories'].head(10))
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.bar(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10))
plt.title('Very Active Minutes by Date')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.show()

import matplotlib.pyplot as plt
print(df.columns.to_list())
plt.figure(figsize = (10,5))
plt.bar(df['ActivityDate'].astype(str), df['TotalSteps'],color='skyblue')
plt.xlabel('ActivityDate')
plt.ylabel('TotalSteps')
plt.title('TotalSteps by ActivityDate')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize = (10,5))
plt.barh(df['ActivityDate'].head(5), df['TotalDistance'].head(5),color='skyblue')
plt.title('TotalDistance by ActivityDate')
plt.show()

plt.figure(figsize = (10,5))
plt.scatter(df['TotalSteps'].head(20),df['TotalDistance'].head(20))
plt.title('TotalSteps vs TotalDistance')
plt.xlabel('TotalSteps')
plt.ylabel('TotalDistance')
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (10,5))
plt.plot(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10),linestyle='--')
plt.title('VeryActiveMinutes by ActivityDate')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (10,5))
plt.plot(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10),linestyle='-',label='Activty')
plt.plot(df['ActivityDate'].head(10), df['FairlyActiveMinutes'].head(10),linestyle='--',label='Fairly Active')
plt.title('VeryActiveMinutes by ActivityDate')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
pf = pd.read_csv('/content/dailyActivity_merged.csv')
plt.figure(figsize = (10,5))
plt.plot(pf['ActivityDate'].head(10), df['TotalSteps'].head(10),label='Steps', linestyle='-')
plt.plot(pf['ActivityDate'].head(10),df['TrackerDistance'].head(10),label='Distance', linestyle='--')
plt.title('Multiple line style ')
plt.xlabel('ActivityDate')
plt.ylabel('values')
plt.legend()
plt.show()

plt.figure(figsize = (10,5))
plt.pie(df['TotalDistance'].head(5),labels= df['ActivityDate'].head(5),autopct='%1.1f%%')
plt.title('TotalDistance by ActivityDate')
plt.show()

labels=df["ActivityDate"].head(10)
values=df["Calories"].head(10)
explode=(0.2,0,0,0,0,0,0,0,0,0)
plt.pie(values,labels=labels, explode=explode,autopct='%1.1f%%',shadow=True,startangle=90)
plt.title('Calories by ActivityDate')
plt.show()

