# -*- coding: utf-8 -*-
"""pandas prathibha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLcxXb6yMD17XvhYQC1y30jQ9aApGMw_
"""

import numpy as np
import pandas as pd

"""# missing data"""

d = {'A': [1,2, np.nan], 'B':[5, np.nan, np.nan],'C':[1,2,3]}
df = pd.DataFrame(d)
df

"""## drop nan method"""

df.dropna()

df.dropna(axis = 0)

df.dropna(axis = 1)

"""## filling value"""

df

df.fillna(value = 'Filling Value')

df = pd.DataFrame(d)
a = df['A'].fillna(value = df['A'].mean())
df

a

df

df['A'].fillna(value = df['A'].mean())

df

df.fillna??
df['A'].fillna(value = df['A'].mean(), inplace = True)
df

"""# Group By"""

data = {
    'Company':['Google', 'Google', 'MSFT', 'FB','FB','IBM'],
    'Person': ['Sam','Nihad','Any','Van','Rakib','Ovi'],
    'Sales': [200, 120, 340, 124, 243, 350]
}
df = pd.DataFrame(data)
df

byComp = df.groupby('Company')
byComp.mean(numeric_only=True)

byComp.sum()

df

byComp.std(numeric_only=True)

df.groupby('Company').count()

df

df.groupby('Company').describe()

"""# Merging, Joining and Concatenating

# Concatenating
"""

df1 = pd.DataFrame(np.random.randint(1, 20, size = (4, 3)), [1,2,3,4], ['W', 'X', 'Y'])
df2 = pd.DataFrame(np.random.randint(20,40, size = (4, 3)), [5,6,7,8], ['W', 'X', 'Y'])
df3 = pd.DataFrame(np.random.randint(40,60, size = (4, 3)), [9,10,11,12], ['W', 'X', 'Y'])
df1

df2

df3

farme = [df1, df2, df3]
pd.concat(farme)

pd.concat(farme, axis = 1)

"""## Merging"""

left = {
    'key':['k0','k1','k2','k3'],
    'A':[10,20,30,40],
    'B':[1,2,3,4]
}
right = {
    'key':['k0','k1','k2','k3'],
    'C':[100,200,300,400],
    'D':[11,12,13,14]
}
left = pd.DataFrame(left)
right = pd.DataFrame(right)
left

right

pd.merge(left, right, on='key')

pd.merge??

"""## Joining"""

left = {
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2']
}
right = {
    'C':['C0','C2','C3'],
    'D':['D0','D2','D3']
}
left = pd.DataFrame(left, index = ['k0','k1','k2'])
right = pd.DataFrame(right, index = ['k0','k2','k3'])
left

right

left.join(right, how = 'inner')

left.join??

"""# Operations"""

df = pd.DataFrame({
    'col1':[444,555,666,444],
    'col2':[1,2,3,4],
    'col3':['abc','def','ghi','xyz']
})
df

df['col1'].unique()

df['col1'].nunique()

df['col1'].value_counts()

"""## Apply Method"""

def times2(x):
    return 2*x
df['col2'].apply(times2)

df['col2'].apply(lambda x:x**2)

"""# Reading File"""

df = pd.read_csv('/content/dailyActivity_merged.csv')
df

df.head(10)

df.head()

df.tail()

df.columns

df.columns.to_list()

df.info()

df.nunique()

df.head()

df['20% Dis'] = df['Calories'].apply(lambda x: x*(20/100))
df.head()

df['Payment'] = df['Calories'] - df['20% Dis']
df.head()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.plot(df['ActivityDate'].head(40), df['Calories'].head(40))
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.plot(df['ActivityDate'].head(20), df['TotalSteps'].head(20))
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.plot(df['ActivityDate'].head(20), df['TotalDistance'].head(20))
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.plot(df['ActivityDate'].head(10), df['TotalSteps'].head(10))
plt.title('Total Steps by Date')
plt.xlabel('ActivityDate')
plt.ylabel('TotalSteps')
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (12,6))
plt.bar(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10))
plt.title('Very Active Minutes by Date')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.show()

import matplotlib.pyplot as plt
print(df.columns.to_list())
plt.figure(figsize = (10,5))
plt.bar(df['ActivityDate'].astype(str), df['TotalSteps'],color='skyblue')
plt.xlabel('ActivityDate')
plt.ylabel('TotalSteps')
plt.title('TotalSteps by ActivityDate')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize = (10,5))
plt.plot(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10),label='VeryActiveMinutes')
plt.title('VeryActiveMinutes by ActivityDate')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.legend()
plt.show()

labels=df['ActivityDate'].head(15)
values=df['TotalDistance'].head(15)
plt.figure(figsize=(7,7))
plt.pie(values,labels=labels,autopct='%1.1f%%')
plt.title("Total Steps Pie Chart")
plt.show()

plt.figure(figsize = (10,5))
plt.pie(df['FairlyActiveMinutes'].head(10),labels= df['VeryActiveMinutes'].head(10),autopct='%1.1f%%')
plt.title('FairlyActiveMinutes by VeryActiveMinutes')
plt.show()

plt.figure(figsize = (10,5))
plt.pie(df['TotalDistance'].head(5),labels= df['ActivityDate'].head(5),autopct='%1.1f%%')
plt.title('TotalDistance by ActivityDate')
plt.show()

labels=df["ActivityDate"].head(10)
values=df["Calories"].head(10)
explode=(0.2,0,0,0,0,0,0,0,0,0)
plt.pie(values,labels=labels, explode=explode,autopct='%1.1f%%',shadow=True,startangle=90)
plt.title('Calories by ActivityDate')
plt.show()

plt.figure(figsize = (10,5))
plt.scatter(df['TotalSteps'].head(20),df['TotalDistance'].head(20))
plt.title('TotalSteps vs TotalDistance')
plt.xlabel('TotalSteps')
plt.ylabel('TotalDistance')
plt.show()

plt.figure(figsize = (10,5))
plt.hist(df['TotalSteps'].head(10),bins=10)
plt.title('TotalSteps Histogram')
plt.xlabel('TotalSteps')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize = (10,5))
plt.barh(df['ActivityDate'].head(5), df['TotalDistance'].head(5),color='skyblue')
plt.title('TotalDistance by ActivityDate')
plt.show()

plt.figure(figsize = (10,5))
plt.bar(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10),label='VeryActiveMinutes')
plt.title('VeryActiveMinutes by ActivityDate')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (10,5))
plt.plot(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10),linestyle='--')
plt.title('VeryActiveMinutes by ActivityDate')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize = (10,5))
plt.plot(df['ActivityDate'].head(10), df['VeryActiveMinutes'].head(10),linestyle='-',label='Activty')
plt.plot(df['ActivityDate'].head(10), df['FairlyActiveMinutes'].head(10),linestyle='--',label='Fairly Active')
plt.title('VeryActiveMinutes by ActivityDate')
plt.xlabel('ActivityDate')
plt.ylabel('VeryActiveMinutes')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
pf = pd.read_csv('/content/dailyActivity_merged.csv')
plt.figure(figsize = (10,5))
plt.plot(pf['ActivityDate'].head(10), df['TotalSteps'].head(10),label='Steps', linestyle='-')
plt.plot(pf['ActivityDate'].head(10),df['TrackerDistance'].head(10),label='Distance', linestyle='--')
plt.title('Multiple line style ')
plt.xlabel('ActivityDate')
plt.ylabel('values')
plt.legend()
plt.show()

fig,ax=plt.subplots(1,2,figsize=(10,5))
ax[0].plot(df['ActivityDate'].head(5), df['VeryActiveMinutes'].head(5))
ax[0].set_title("VeryActiveMinutes")
ax[1].plot(df['ActivityDate'].head(5),df['FairlyActiveMinutes'].head(5))
ax[1].set_title("FairlyActiveMinutes")
plt.show()

fig,ax=plt.subplots(1,2,figsize=(10,5))
ax[0].bar(df['ActivityDate'].head(5), df['TotalSteps'].head(5))
ax[0].set_title("TotalSteps")
ax[1].plot(df['ActivityDate'].head(5),df['TotalDistance'].head(5))
ax[1].set_title("TotalDistance")
plt.show()

fig,ax=plt.subplots(1,2,figsize=(10,5))
ax[0].pie(df['TotalSteps'].head(5),labels=df['ActivityDate'].head(5),autopct='%1.1f%%')
ax[0].set_title("TotalSteps")
ax[1].pie(df['TotalDistance'].head(5),labels=df['ActivityDate'].head(5),autopct='%1.1f%%')
ax[1].set_title("TotalDistance")
plt.show()

plt.plot(df['ActivityDate'].head(5),df['TotalSteps'].head(5),color='purple',linestyle='--')
plt.xticks(rotation=45)
plt.yticks([10000,12000,14000,16000,18000])
plt.show()

x=[3/24,3/25,3/26,3/27,3/28]
y=[10000,12000,14000,16000,18000]
plt.plot(x,y,color='darkgreen')
plt.show()

plt.plot(df['ActivityDate'].head(5),df['TotalSteps'].head(5),color='darkgreen')
plt.xticks(['3/25','3/26','3/27','3/28','3/29'])
plt.yticks([10000,12000,14000,16000,18000])
plt.show()

fig,ax=plt.subplots()
fig.set_size_inches(12,5)
x=df['ActivityDate'].head(5)
y1=df['TotalSteps'].head(5)
ax.plot(x,y1,color='green')
ax.set_title("Main Graph")
ax2=fig.add_axes([0.6,0.5,0.25,0.25])
y2=df['TotalDistance'].head(5)
ax2.plot(x,y2,color='purple')
ax2.set_title("Inside Graph")
plt.show()

x1=['3/25','3/26','3/27','3/28','3/29']
y1=[11000,17000,12000,13000,12765]
fig,ax=plt.subplots(figsize=(12,5))
fig.set_size_inches(12,5)
ax.plot(x1,y1,color='darkgreen')
ax.set_title("Main Graph")
x2=['3/25','3/26','3/27','3/28','3/29']
y2=[7.11,11.55,8.53,8.93,7.85]
ax2=fig.add_axes([0.6,0.5,0.25,0.25])
ax2.plot(x2,y2,color='red')
ax2.set_title("Inside Graph")
plt.show()