# -*- coding: utf-8 -*-
"""plotly prathibha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1niR4O4SnQsA4tw6ybLBnuWR63wJmtsy8

Plotly
"""

import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv('/content/dailyActivity_merged.csv')
df

"""Plotly Express Function"""

fig=px.scatter(df,x="VeryActiveDistance",y="TotalSteps",size="TotalDistance",color="ActivityDate",title="Activity Scatter Plot")
fig.show()

fig=px.line(df.head(100),x="VeryActiveDistance",y="TotalSteps",color="ActivityDate",title="Activity line Plot")
fig.show()

fig=px.bar(df,x="TrackerDistance",y="TotalSteps",color="FairlyActiveMinutes",title="Activity Bar Plot")
fig.show()

data={"Product":["A","B","C","D"],"Sales":[120,150,90,200]}
df=pd.DataFrame(data)
fig=px.bar(df,x="Product",y="Sales",color="Product",title="Product Sale Bar Chart")
fig.show()

data={"Product":["A","B","C","D"],"Sales":[120,150,90,200]}
df=pd.DataFrame(data)
fig=px.pie(df,names="Product",values="Sales",title="Product Sale Pie Chart")
fig.show()

data={"Marks":[45,67,89,56,78,90,45,67]}
df=pd.DataFrame(data)
fig=px.histogram(df,x="Marks",title="Marks Histogram",nbins=5,color="Marks")
fig.show()

data={"Marks":[45,67,89,56,78,90,45,67]}
df=pd.DataFrame(data)
fig=px.histogram(df,y="Marks",title="Marks Histogram",color="Marks")
fig.show()

data={"Student":["A","B","C","D","E","F","G","H"],"Marks":[45,67,89,56,78,90,45,67]}
df=pd.DataFrame(data)
fig=px.box(df,x="Student",y="Marks",title="Marks Box",color="Student")
fig.show()

data={"x_value":[10,20,30,40,50],"y_value":[5,15,25,35,45],"z_value":[2,4,6,8,10]}
df=pd.DataFrame(data)
fig=px.scatter_3d(df,x="x_value",y="y_value",z="z_value",color="z_value",title="3D Scatter Plot",size="z_value")
fig.show()

"""Graph Objects and Layout Functions"""

import plotly.graph_objects as go
fig=go.Figure(data=go.Scatter(x=[1,2,3,4],y=[10,15,13,20],mode="lines+markers"))
fig.show()

import plotly.graph_objects as go
fig=go.Figure(data=go.Bar(x=["A","B","C","D"],y=[10,20,30,40]))
fig.show()

fig=go.Figure()
fig.add_trace(go.Scatter(x=[1,2,3,4],y=[10,15,13,20],mode="lines",name="Line Plot"))
fig.show()

"""3D Graph"""

data={"x_value":[10,20,30,40,50],"y_value":[5,15,25,35,45],"z_value":[2,4,6,8,10]}
df=pd.DataFrame(data)
fig=px.scatter_3d(df,x="x_value",y="y_value",z="z_value",color="z_value",title="3D Scatter Plot")
fig.show()

df=pd.DataFrame({"X":[10,20,30,40,50],"Y":[5,15,25,35,45],"Z":[2,4,6,8,10]})
fig=px.line_3d(df,x="X",y="Y",z="Z",title="3D Line Chart")
fig.show()

z=np.array([[1,2,3],[4,5,6],[7,8,9]])
fig=go.Figure(data=[go.Surface(z=z)])
fig.update_layout(title="3D Surface Plot",autosize=False,width=500,height=500)
fig.show()

import plotly.graph_objects as go
fig=go.Figure(data=[go.Mesh3d(x=[10,20,30,40,50],y=[5,15,25,35,45],z=[2,4,6,8,10])])
fig=go.Figure(data=[go.Mesh3d(x=df['X'],y=df['Y'],z=df['Z'])])
fig.show()

fig=go.Figure(data=go.Isosurface(x=[0,0,0,1,1,1],y=[0,1,2,0,1,2],z=[0,0,0,1,1,1],
                                 value=[1,2,3,4,5,6],isomin=2,isomax=5,surface_count=3))
fig.update_layout(scene=dict(xaxis_title="X",yaxis_title="Y",zaxis_title="Z"))
fig.show()

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-5, 5, 50)
y = np.linspace(-5, 5, 50)
X, Y = np.meshgrid(x, y)
Z = np.sin(np.sqrt(X**2 + Y**2))
fig = plt.figure(figsize=(10, 7))
ax = plt.axes(projection='3d')
ax.plot_wireframe(X, Y, Z, color='blue', rstride=2, cstride=2)
ax.set_title("3D Mesh Wireframe")
ax.set_xlabel("X Axis")
ax.set_ylabel("Y Axis")
ax.set_zlabel("Z Axis")
plt.show()

import numpy as np
import plotly.graph_objects as go
X, Y, Z = np.mgrid[-5:5:40j, -5:5:40j, -5:5:40j]
values = X**2 + Y**2 + Z**2
fig = go.Figure(data=go.Isosurface(
x=X.flatten(),y=Y.flatten(),z=Z.flatten(),value=values.flatten(),isomin=10,isomax=25,
caps=dict(x_show=False, y_show=False, z_show=False)))
fig.show()