# -*- coding: utf-8 -*-
"""seaborn prathibha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCZAa0CZP-7YftqQtLOaKVK1IsHqJrtk
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/dailyActivity_merged.csv')
df

plt.figure(figsize = (12,5))
sns.stripplot(x='ActivityDate', y='TotalSteps', data=df.head(10))
plt.title("Strip Plot")
plt.xlabel("Activity Date")
plt.ylabel("Total Steps")
plt.show()

df_10=df.head(10)
plt.figure(figsize=(12,5))
sns.swarmplot(x='ActivityDate', y='TotalSteps', data=df_10,color='purple',size=10)
plt.title("Swarm Plot")
plt.xlabel("Activity Date")
plt.ylabel("Total Steps")
plt.tight_layout()
plt.show()

df_10=df.head(10)
plt.figure(figsize=(12,5))
sns.barplot(x='ActivityDate', y='TotalSteps', data=df_10,color='purple')
plt.title("Swarm Plot")
plt.xlabel("Activity Date")
plt.ylabel("Total Steps")
plt.tight_layout()
plt.show()

df_10=df.head(10)
plt.figure(figsize=(12,4))
sns.countplot(x='TrackerDistance', data=df_10,color='yellow')
plt.title("Swarm Plot")
plt.xlabel("TrackerDistance")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

df_10=df.head(10)
plt.figure(figsize=(12,5))
sns.boxplot(x='ActivityDate', y='TotalSteps', data=df_10,color='purple')
plt.title("box Plot")
plt.xlabel("Activity Date")
plt.ylabel("Total Steps")
plt.tight_layout()
plt.show()

df_10=df.head(10)
plt.figure(figsize=(12,5))
sns.boxplot(x='ActivityDate', y='TotalSteps', hue='ActivityDate',palette='Set2',width=0.6,linewidth=1.5,data=df_10,
            fliersize=5, color='purple')
plt.title("ActivityDate Distribution by TotalSteps ")
plt.xlabel("Activity Date")
plt.ylabel("Total Steps")
plt.xticks(rotation=45)
plt.legend(title='ActivityDate',bbox_to_anchor=(1.05,1),loc='upper right')
plt.tight_layout()
plt.show()

df_10=df.head(10)
plt.figure(figsize=(12,5))
sns.violinplot(x='ActivityDate', y='TotalSteps',data=df_10, color='purple')
plt.title("ActivityDate Distribution by TotalSteps ")
plt.xlabel("Activity Date")
plt.ylabel("Total Steps")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Relational plot"""

plt.figure(figsize=(12,6))
sns.relplot(x='ActivityDate', y='TotalSteps', data=df.head(5))
plt.show()

sns.scatterplot(x='TotalSteps', y='Calories',hue='ActivityDate',data=df.head(5))
plt.show()

sns.lineplot(x='ActivityDate', y='TotalSteps', hue='Id',data=df.head(5))
plt.show()

"""Distribution Plots"""

sns.displot(x='TotalSteps',data=df.head(5),color='purple')
plt.show()

sns.histplot(x='TotalSteps',data=df.head(5),color='green')
plt.show()

sns.histplot(x='TotalSteps',data=df.head(5),kde=True, color='yellow')
plt.show()

sns.histplot(x='TotalSteps',data=df.head(5),bins=10,color='pink')
plt.show()

sns.kdeplot(x='Calories',y='TotalDistance',data=df.head(10),color='purple')
plt.show()

sns.kdeplot(x='Calories',y='TotalDistance',data=df.head(100),color='purple',fill=True)
plt.show()

sns.ecdfplot(x='Calories',data=df.head(10),hue='ActivityDate',color='purple')
plt.show()

sns.rugplot(x='Calories',data=df.head(10),height=0.3,color='purple')
plt.show()

"""Categorical Plots"""

sns.catplot(x='ActivityDate',y='TotalSteps',data=df.head(15),kind='strip',color='purple')
plt.show()

sns.boxplot(x='Calories',data=df.head(5),hue='Id' ,color='pink')
plt.show()

sns.violinplot(x='Calories',data=df.head(5),color='brown')
plt.show()

sns.barplot(x='Calories',y='TotalSteps',data=df.head(10),color='purple')
plt.show()

sns.countplot(x='ActivityDate',data=df.head(5),color='blue')
plt.show()

sns.stripplot(x='ActivityDate',y='TotalSteps',data=df.head(5),color='purple')
plt.show()

sns.swarmplot(x='ActivityDate',y='TotalSteps',data=df.head(5),hue='Calories',color='purple')
plt.show()

"""Regression Plots"""

sns.lmplot(x='TotalSteps',y='Calories',data=df.head(10))
plt.show()

sns.lmplot(x='TotalSteps',y='Calories',data=df.head(10),fit_reg=False)
plt.show()

sns.regplot(x='TotalSteps',y='Calories',data=df.head(10),marker='o',color='olive')
plt.show()

sns.residplot(x='TotalSteps',y='Calories',data=df.head(10),color='teal')
plt.show()

"""Matrix Plots"""

corr=df.corr(numeric_only=True)
sns.heatmap(corr,annot=True)
plt.show()

sns.heatmap(corr,annot=True,cmap='coolwarm')
plt.show()

corr=df.corr(numeric_only=True)
sns.clustermap(corr,annot=True,cmap='coolwarm',linewidths=0.5)
plt.show()

"""season plot"""

from statsmodels.tsa.seasonal import seasonal_decompose
result=seasonal_decompose(df['TotalSteps'],model='additive',period=12)
result.plot()
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt
result=seasonal_decompose(df['TotalDistance'],model='additive',period=12)
result.seasonal.plot()
plt.title('Seasonal Graph')
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt
result=seasonal_decompose(df['TotalDistance'],model='additive',period=12)
result.trend.plot()
plt.title('Seasonal Graph')
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt
result=seasonal_decompose(df['TotalDistance'],model='additive',period=12)
result.resid.plot()
plt.title('Seasonal Graph')
plt.show()

from statsmodels.tsa.seasonal import STL
import matplotlib.pyplot as plt
stl=STL(df['Calories'],period=7)
result=stl.fit()
plt.plot(result.resid)
plt.title('STL Seasonal Graph')
plt.show()

from statsmodels.tsa.seasonal import STL
import matplotlib.pyplot as plt
stl=STL(df['Calories'],period=12)
result=stl.fit()
plt.plot(result.trend)
plt.title('STL Seasonal Graph')
plt.show()

from statsmodels.tsa.seasonal import STL
import matplotlib.pyplot as plt
stl=STL(df['Calories'],period=12)
result=stl.fit()
plt.plot(result.seasonal)
plt.title('STL Seasonal Graph')
plt.show()

from statsmodels.tsa.seasonal import STL
stl=STL(df['TotalSteps'],period=12)
result=stl.fit()
result.plot()
plt.show()

from statsmodels.tsa.statespace.sarimax import SARIMAX
model=SARIMAX
model=SARIMAX(df['TotalSteps'],order=(1,1,1),seasonal_order=(1,1,1,12))
model_fit=model.fit()
model_fit.summary()

from prophet import Prophet
df=df.rename(columns={'ActivityDate':'ds','TotalSteps':'y'})
model=Prophet(yearly_seasonality=True,weekly_seasonality=True)
model.fit(df)
future=model.make_future_dataframe(periods=30)
forecast=model.predict(future)
model.plot(forecast)
plt.show()

plt.plot(df['ActivityDate'].head(5),df['TotalSteps'].head(5),color='darkgreen')
plt.xticks(['3/25','3/26','3/27','3/28','3/29'])
plt.yticks([10000,12000,14000,16000,18000])
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt
x=['3/25','3/26','3/27','3/28','3/29']
y=[11004,17609,12736,13231,12041]
result=seasonal_decompose(y,model='additive',period=2)
plt.plot(x,result.seasonal)
plt.xlabel('Date')
plt.ylabel('Total Steps')
plt.title('Seasonal Graph')
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt
x=['3/25','3/26','3/27','3/28','3/29']
y=[11004,17609,12736,13231,12041]
result=seasonal_decompose(y,model='additive',period=2)
plt.plot(x,result.seasonal)
plt.xticks(['3/25','3/26','3/27','3/28','3/29'])
plt.yticks([10000,12000,14000,16000,18000])
plt.xlabel('Date')
plt.ylabel('Total Steps')
plt.title('Seasonal Graph')
plt.show()

