# -*- coding: utf-8 -*-
"""Untitled1.ipynb test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PKihPBRqAPnztyseQ7r8ZbUDdFtm5rH
"""

age=input("enter your age")
if int(age)>=18:
    print("eligible to vote")
else:
    print("eligible cannot to vote")

charge=input("enter the charge")
if int(charge)<=35:
    print("charge is low")
elif int(charge)<=75:
    print("charge is medium ")
else:
    print("charge is high")

num=input("enter the number")
if int(num)<=9:
    print("single digit number")
elif int(num)<=99:
    print("two digit number")
elif int(num)<=999:
    print("three digit number")
elif int(num)<=5000:
    print("four digit number")
else:
    print("number is greater than 5000")

user={"user1":"tvk","user2":"abc","user3":"vijay"}
password={"tvk":"123","abc":"456","vijay":"789"}
user1=input("enter the userid:")
if user1 in user.values():
    password1=input("enter the password: ")
    if password1==password.get(user1):
      print("login successfull")
    elif password1!=password.get(user1):
        print("invalid password")
elif user1 not in user.values():
    print("invalid user name")
else:
    print("login is failed")